name: facility
channels:
    - defaults
dependencies:
    - numpy
    - matplotlib
    - pandas
    - pytest
    - tqdm
    - scipy
    - ray
    - joblib
    - seaborn
    - pip
    - jupyter
    - pip:
          - geopy
          - EoN
          - ortools